// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMt82QERpObpxvmQTE_H0iUJ-pe41Cshs',
    appId: '1:288589730569:web:74c6dcb394d8e05c5379d8',
    messagingSenderId: '288589730569',
    projectId: 'school-management-1e59f',
    authDomain: 'school-management-1e59f.firebaseapp.com',
    storageBucket: 'school-management-1e59f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm1A22JOovbuUd4dtrS1273VNehWtj2y0',
    appId: '1:288589730569:android:d812fa56b6ad349b5379d8',
    messagingSenderId: '288589730569',
    projectId: 'school-management-1e59f',
    storageBucket: 'school-management-1e59f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4DBvsStx9r_e2nZL8LnVNmw-VXGRtCdQ',
    appId: '1:288589730569:ios:da43c0954ac592a55379d8',
    messagingSenderId: '288589730569',
    projectId: 'school-management-1e59f',
    storageBucket: 'school-management-1e59f.appspot.com',
    iosClientId: '288589730569-76bmdl51k2pt1mfd55topjg24dpp8df5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4DBvsStx9r_e2nZL8LnVNmw-VXGRtCdQ',
    appId: '1:288589730569:ios:da43c0954ac592a55379d8',
    messagingSenderId: '288589730569',
    projectId: 'school-management-1e59f',
    storageBucket: 'school-management-1e59f.appspot.com',
    iosClientId: '288589730569-76bmdl51k2pt1mfd55topjg24dpp8df5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStudyApp',
  );
}
